version: "3"
services:
  wordpress:
    build: ./my-wordpress
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always
    environment:
      WORDPRESS_DB_HOST: "db:3306"
    env_file: .env
    volumes:
      - ./themes/bones:/var/www/html/wp-content/themes/bones
  db:
    image: mysql:latest
    env_file: .env
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      # - ./db_data/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
volumes:
  db_data:
    driver: local