version: "2"
services:
  wordpress:
    build: ./my-wordpress
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: "mysql:3306"
    env_file: .env
    volumes:
      - ./themes/bones:/var/www/html/wp-content/themes/bones
  mysql:
    image: mysql:latest
    env_file: .env
    volumes:
      - data-mysql:/var/lib/mysql
      - ./data-mysql/mysql.dump.sql:/docker-entrypoint-initdb.d/install_wordpress.sql
volumes:
  data-mysql:
    driver: local